
import React from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { 
  Github, 
  HeartHandshake, 
} from 'lucide-react';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import Link from 'next/link';
import Image from 'next/image';

// Logo attribution links
const logoAttributions = [
  {
    title: "Icon by Freepik",
    url: "https://www.freepik.com/icon/stack_1147142",
    description: "Icon sourced from Freepik"
  },
  {
    title: "Font generator",
    url: "https://www.textstudio.com",
    description: "Font generated by textstudio.com used for the Logo"
  }
];

const DotGrid = () => (
  <div className="absolute inset-0 overflow-hidden">
    {/* Bottom fade gradient only */}
    <div className="absolute inset-x-0 bottom-0 h-40 bg-gradient-to-t from-gray-50 to-transparent z-10" />
    <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
      <pattern id="dot-pattern" x="0" y="0" width="40" height="40" patternUnits="userSpaceOnUse">
        <circle cx="20" cy="20" r="1" fill="#3e3e3e" opacity="0.5" />
      </pattern>
      <rect width="100%" height="100%" fill="url(#dot-pattern)" />
    </svg>
  </div>
);

export default function AboutPage() {
  return (
    <div className="bg-white">
      <DotGrid />
        <Navbar />
      {/* Hero Section */}
      <section className="pt-24 pb-12 bg-gradient-to-b from-blue-50 to-white h-screen overflow-hidden flex flex-col">
        <Image src={"/logo2.png"} alt='logo' width={500} height={200} className='self-center'/>
        <div className="container mx-auto px-4 text-center">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">
            Our Mission
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Making collaboration seamless and accessible for teams everywhere. 
            BoardScape is built on the belief that great ideas can come from 
            anyone, anywhere, at any time.
          </p>
        </div>
        <Image src={"/empty-search.svg"} width={400} height={800} alt='searching' className='self-center' />
      </section>

      {/* Open Source Section */}
      <section className="py-16 bg-gray-50">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto text-center">
            <HeartHandshake className="w-16 h-16 mx-auto mb-6 text-blue-600" />
            <h2 className="text-3xl font-bold mb-6">Open Source & Community Driven</h2>
            <p className="text-lg text-gray-600 mb-8">
              BoardScape is proudly open source and built with modern technologies. 
              We believe in the power of community and welcome contributions from developers 
              around the world.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button size="lg" className="gap-2" asChild>
                <Link href={"https://github.com/ABC/BoardScape"} target='_blank'>
                  <Github className="w-5 h-5" />
                  View on GitHub
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Tech Stack Section */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-12">Built With</h2>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-8 max-w-4xl mx-auto">
            {[
              'Next.js 14', 'TypeScript', 'Tailwind CSS', 
              'Convex', 'Liveblocks', 'Clerk'
            ].map((tech) => (
              <Card key={tech} className="border-none shadow-sm hover:shadow-md transition-shadow">
                <CardContent className="p-4 text-center">
                  <div className="font-medium">{tech}</div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Attribution Section */}
      <section className="py-16 bg-gray-50">
        <div className="container mx-auto px-4">
          <div className="max-w-2xl mx-auto">
            <h2 className="text-2xl font-bold text-center mb-8">Attributions</h2>
            <div className="space-y-4">
              {logoAttributions.map((attribution) => (
                <Card key={attribution.title}>
                  <CardContent className="p-6">
                    <div className="flex justify-between items-start gap-4">
                      <div>
                        <h3 className="font-semibold mb-1">{attribution.title}</h3>
                        <p className="text-gray-600 text-sm">{attribution.description}</p>
                      </div>
                      <Button variant="outline" size="sm" asChild>
                        <a href={attribution.url} target="_blank" rel="noopener noreferrer">
                          Visit
                        </a>
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </div>
  );
}
